name: Prepare Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Override version name (or use the latest tag)'
        required: false
      release_notes_url:
        description: 'Release notes URL for Firebase'
        required: false

jobs:
  prepare_release:
    name: "New tag and release branch"
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Configure Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Prepare release
        run: ./gradlew :app:prepareRelease -PversionName="${{ github.event.inputs.version_name }}" -PreleaseNotesUrl="${{ github.event.inputs.release_notes_url }}"
