name: Verify build

permissions: read-all

on:
  pull_request:
    branches:
      - main

jobs:
  debug_build:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Verify Debug Build
        run: ./gradlew assembleDebug
